### ISSUE TITLE
Feature Request: Variables for default pomodoro/breaks length

### ISSUE THREAD

**Issue by saintsebastian** [notwaldorf/tiny-care-terminal#116]
I love this feature in tct, but I tend to like longer pomodoros and breaks (50/15). It would be great if user can set up default lengths together with the rest of config, but still will be able to update them temporarily on the fly.

My intuition is that it's a small change, so I would write it myself, if anyone else finds it useful.

**Comment by maxcell** [comment]
This is an amazing suggestion @saintsebastian! I don't particularly contribute to this codebase, but I wouldn't mind trying to help this come along.

**Comment by saintsebastian** [comment]
@maxcell I'm glad I'm not alone in this :) If you want to add something here is [my PR](https://github.com/notwaldorf/tiny-care-terminal/pull/117)

**Comment by maxcell** [comment]
@saintsebastian I love it a lot! I mentioned on the PR might just be good to put in if it is minutes/seconds/etc. for setting the time. It lets people who might not be familiar with what a pomodoro is and how to set up the time. Otherwise I think this excellent! Great job with also keeping the default state available. I am not sure if we need to worry about when a user changes the state manually because I know that's something they can do too.

**Comment by maxcell** [comment]
@saintsebastian You did awesome! I think you should close this and be proud of your splendid work!

**Comment by mojoaxel** [comment]
@saintsebastian also a big thx from me!
