### ISSUE TITLE
Where do env keys go?

### ISSUE THREAD

**Issue by mike3run** [notwaldorf/tiny-care-terminal#16]
I don't see that mentioned in the repo 😭 

Maybe a tiny update to the readme to help us new users?

**Comment by AdamasFR** [comment]
Hi !

You can go see in https://github.com/notwaldorf/tiny-care-terminal/blob/master/sample.env. Actually, the file provide all you need to get started ! In order to enter a env key, you just write in your terminal "export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'".

More explications about the export command line here : https://linuxconfig.org/learning-linux-commands-export (or using "man export" in your term I believe).

I struggled with it at first, I'm a Linux noob, but in the end, everything seems to work !

**Comment by kaxcode** [comment]
@mike3run if you are using Mac Terminal or iterm2 and you also use zsh (shell) you would put everything that is in the sample.env into the .zshrc file. I copied and pasted it to the bottom of my .zshrc file and added the twitter API information and filled out everything else.

**Comment by mike3run** [comment]
awesome im also at mac and iterm but with fish shell so yeah good to now, i'll export that stuff as well

**Comment by notwaldorf** [comment]
Awesome, thanks for sorting this out folks! Closing, as it seems like @mike3run has it figured out :)
