### ISSUE TITLE
Issues when display: fonts

### ISSUE THREAD

**Issue by vanloc0301** [notwaldorf/tiny-care-terminal#44]
OS: Manjaro.
Shell: zsh.
Version: latest.
Terminal Program: terminator.
Node Version: v 7.7.3.

Seem I can't see a character's special.
I tried to install fonts from [https://github.com/powerline/fonts](url)

In my terminal, a show like:

![screenshot_2017-04-22_10-19-42](https://cloud.githubusercontent.com/assets/4168981/25300936/3cb5054a-2745-11e7-9882-4ad5c53806ed.png)

You can see font seem broken. Characters before: ```Today```, ```Week```, ...

**Comment by Garbee** [comment]
I use the [Iosevka font](https://github.com/be5invis/Iosevka) and don't have any problems with the emoji's. In terminator as well with either zsh or fish. Just tested with Anonymous Pro for Powerline as well and it is working as expected.

The only thing that could be done internally to the project here is removing the icons completely. As far as I know detecting support isn't easy since the problem occurs in the rendering process. Not sure if that is something that is desired though as it then makes the dashboard more bland and less inviting where the icons are supported.

This could be due to the way Arch is rendering fonts itself. I'll setup a VM tomorrow to test. (I run Elementary OS as my primary.)

**Comment by droM4X** [comment]
Same on linux mint (xfce) too (with Inconsolata font)
I tried the Anonymous Pro, but nothing changes.

**Comment by vanloc0301** [comment]
@Garbee Edited: my OS current is Manjaro Xfce environment, it's also not working.

I tried with the almost font.

**Comment by notwaldorf** [comment]
This is a classic problem with emoji -- on a OS, it's usually just one font that knows how to draw emoji (like AppleColorEmoji, Noto Emoji etc), and all other fonts fallback to it. It looks like either no emoji work on your OS, or the terminal doesn't know how to use them.

You can try these instructions here to see if you can install an emoji font: http://www.omgubuntu.co.uk/2016/08/enable-color-emoji-linux-google-chrome-noto

Closing, as this is a terminal configuration bug that I can't fix from the dashboard :(
