### ISSUE TITLE
Commits graphs don't display properly

### ISSUE THREAD

**Issue by VonKavalier** [notwaldorf/tiny-care-terminal#61]
**Node Version**: v7.8.0
**tiny-core-terminal version**: 1.0.8
**Shell**: bash
**Terminal Program**: terminator
**Operating System**: Ubuntu 16.04

They are not well displayed, like they are trying to be on top of each other. See pic

![tct-bug](https://cloud.githubusercontent.com/assets/21989855/25380052/3808c09c-29af-11e7-8098-f3c43eee3214.png)

**Comment by vspedr** [comment]
Got the same issue as picture above on:
node version 6.10.1,
tiny-care-terminal@1.0.8,
bash
OS X Sierra's default Terminal

It also looks weird on Hyper terminal, but it's a different problem
<img width="594" alt="screen shot 2017-04-25 at 16 38 53" src="https://cloud.githubusercontent.com/assets/9813942/25404277/a69aaa36-29d5-11e7-89b6-cdc0c9a5fc20.png">

**Comment by Garbee** [comment]
Hyper is its own problem.

The graphs I've noticed don't display well when the terminal is under a certain size. So things start to compress. Not sure if the graphing tool used allows for responsive box sizing.

**Comment by VonKavalier** [comment]
Well, I putted it fullscreen when taking the screenshot so I don't think it's about screen sizing

**Comment by Garbee** [comment]
Did you launch `tiny-care-terminal` while it was fullscreen? If so what is the size of the terminal area at that time?

For example, if I launch it in a small window, the columns are compressed. Even when maximizing. However, if I maximize first and then launch the program the columns display properly. This is because the grid sizes are calculated at start-time and not dynamically during run-time.

**Comment by VonKavalier** [comment]
Yes that's it, I need to size terminal as I want first. Thank you, I'll close
